services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - '${MONGO_PORT}:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - backend
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: backend
    restart: always
    ports:
      - '${PORT}:${PORT}'
    environment:
      MONGO_URI: 'mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}?authSource=admin'
    volumes:
      - .env:/app/.env
    networks:
      - backend
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  mongo_data:

networks:
  backend:
